# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I_QMwH0uDuHL2SG6DbjIr0jlBsajZ811
"""

#Solution1
import seaborn as sns
titanic=sns.load_dataset('titanic')

titanic.head()

import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=titanic['age'] , y=titanic['fare'] , mode='markers' ))
fig.show()

#Solution2
import plotly.express as px
df=px.data.tips()
fig = px.box(df, x="total_bill", y="tip")

fig.show()

#Solution3
import plotly.express as px
import seaborn as sns
tips=sns.load_dataset('tips')
fig=px.histogram(tips,x='sex',y='total_bill', color='day', pattern_shape='smoker')
fig.show()

#Solution4
import plotly.express as px
import seaborn as sns
iris=sns.load_dataset("iris")
fig=px.scatter_matrix(iris,color='species')
fig.show()

#Solution5
"""A distplot displays a combination of statistical representations of numerical data,
such as histogram, kernel density estimation or normal curve, and rug plot."""
import plotly.figure_factory as ff
import numpy as np
np.random.seed(1)

x = np.random.randn(1000)
hist_data = [x]
group_labels = ['distplot']

fig = ff.create_distplot(hist_data, group_labels)
fig.show()